# Generated by Django 5.0 on 2026-06-18 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('theme', models.CharField(choices=[('javanese-dark', 'Javanese Malam Emas'), ('floral-light', 'Taman Bunga'), ('modern-minimalist', 'Minimalis Putih')], default='javanese-dark', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('wedding_date', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('opening_text', models.TextField(blank=True)),
                ('closing_text', models.TextField(blank=True)),
                ('watermark', models.BooleanField(default=True)),
                ('music_file', models.FileField(blank=True, null=True, upload_to='music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('akad', 'Akad Nikah'), ('resepsi', 'Resepsi')], max_length=10)),
                ('datetime', models.DateTimeField()),
                ('venue_name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('gmaps_url', models.URLField(blank=True)),
                ('gmaps_embed_url', models.URLField(blank=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitations.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=200)),
                ('bride_parents', models.CharField(max_length=300)),
                ('bride_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bride_bio', models.TextField(blank=True)),
                ('groom_name', models.CharField(max_length=200)),
                ('groom_parents', models.CharField(max_length=300)),
                ('groom_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groom_bio', models.TextField(blank=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couple', to='invitations.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('attending', models.BooleanField()),
                ('pax', models.PositiveIntegerField(default=1)),
                ('wishes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='invitations.invitation')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
