# Generated by Django 5.0 on 2026-06-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='theme',
            field=models.CharField(choices=[('javanese-dark', 'Javanese Malam Emas'), ('floral-light', 'Taman Bunga'), ('modern-minimalist', 'Minimalis Putih'), ('luxury-emerald', 'Zamrud Mewah'), ('rustic-kraft', 'Rustic Kraft'), ('boho-terracotta', 'Senja Terakota')], default='javanese-dark', max_length=30),
        ),
    ]
