# Generated by Django 5.0 on 2026-06-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_invitation_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='livestream_url',
            field=models.URLField(blank=True),
        ),
    ]
