# Generated by Django 5.0 on 2026-06-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_livestream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('ewallet', 'E-Wallet'), ('qris', 'QRIS')], default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='qris_image',
            field=models.ImageField(blank=True, null=True, upload_to='qris/'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
