# Generated by Django 5.0 on 2026-06-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_bankaccount_account_type_bankaccount_qris_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='activation_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='activation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='activation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
