# Generated by Django 5.0 on 2026-06-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_alter_invitation_couple_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='tier',
            field=models.CharField(choices=[('free', 'Gratis'), ('premium', 'Premium'), ('bisnis', 'Bisnis')], default='free', max_length=10),
        ),
    ]
