# Generated by Django 5.0 on 2026-06-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_alter_event_options_event_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Permintaan Aktivasi',
                'verbose_name_plural': 'Permintaan Aktivasi (pending)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invitations.invitation',),
        ),
    ]
