# Generated by Django 5.0 on 2026-06-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0012_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvps', to='invitations.guest'),
        ),
    ]
