# Generated by Django 5.0 on 2026-06-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0013_rsvp_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='dress_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
