# Generated by Django 5.0 on 2026-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0014_invitation_dress_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='wishlist_url',
            field=models.URLField(blank=True),
        ),
    ]
