# Generated by Django 5.0 on 2026-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0016_musicpreset_invitation_music_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='hero_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
