# Generated by Django 5.0 on 2026-06-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0019_alter_invitation_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='theme',
            field=models.CharField(choices=[('javanese-dark', 'Javanese Malam Emas'), ('floral-light', 'Taman Bunga'), ('modern-minimalist', 'Minimalis Putih'), ('luxury-emerald', 'Zamrud Mewah'), ('rustic-kraft', 'Rustic Kraft'), ('boho-terracotta', 'Senja Terakota'), ('burgundy-gold', 'Marun Anggun'), ('dusty-blue', 'Biru Senja'), ('midnight-celestial', 'Langit Malam'), ('sage-botanical', 'Kebun Sage'), ('mauve-rose', 'Mauve Anggun'), ('ivory-classic', 'Klasik Gading'), ('tropical-green', 'Tropis Hijau'), ('lavender-dream', 'Lembayung'), ('coral-peach', 'Koral Hangat'), ('charcoal-marble', 'Marmer Arang'), ('islamic-arabesque', 'Arabesque Emas'), ('navy-gold', 'Navy Klasik'), ('plum-gold', 'Plum Anggur'), ('teal-ocean', 'Teal Samudra'), ('deco-noir', 'Deco Hitam Emas'), ('sunflower-mustard', 'Bunga Matahari'), ('beige-korean', 'Aesthetic Beige'), ('rose-gold', 'Rose Gold'), ('mono-editorial', 'Editorial Mono'), ('royal-purple', 'Ungu Kerajaan'), ('marble-white', 'Marmer Putih')], default='javanese-dark', max_length=30),
        ),
    ]
