# Generated by Django 5.0 on 2026-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0022_alter_invitation_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='theme',
            field=models.CharField(choices=[('javanese-dark', 'Javanese Gold Night'), ('floral-light', 'Flower Garden'), ('modern-minimalist', 'White Minimalist'), ('luxury-emerald', 'Luxury Emerald'), ('rustic-kraft', 'Rustic Kraft'), ('boho-terracotta', 'Terracotta Dusk'), ('burgundy-gold', 'Burgundy Gold'), ('dusty-blue', 'Dusty Blue'), ('midnight-celestial', 'Celestial Night'), ('sage-botanical', 'Sage Garden'), ('mauve-rose', 'Elegant Mauve'), ('ivory-classic', 'Ivory Classic'), ('tropical-green', 'Tropical Green'), ('lavender-dream', 'Lavender Dream'), ('coral-peach', 'Warm Coral'), ('charcoal-marble', 'Charcoal Marble'), ('islamic-arabesque', 'Golden Arabesque'), ('navy-gold', 'Classic Navy'), ('plum-gold', 'Plum Gold'), ('teal-ocean', 'Ocean Teal'), ('deco-noir', 'Art Deco Noir'), ('sunflower-mustard', 'Golden Sunflower'), ('beige-korean', 'Aesthetic Beige'), ('rose-gold', 'Rose Gold'), ('mono-editorial', 'Editorial Mono'), ('royal-purple', 'Royal Purple'), ('marble-white', 'White Marble'), ('celestial-cinematic', 'Celestial 3D'), ('petals-3d', 'Enchanted Petals'), ('aurora-3d', 'Aurora Dream'), ('golden-3d', 'Golden Aura'), ('clouds-3d', 'Ethereal Clouds')], default='javanese-dark', max_length=30),
        ),
    ]
